#!/bin/zsh

mkdir -p ~/.vim/
mkdir -p ~/.config/

ln -s $PWD/.zshrc ~/
ln -s $PWD/.zshenv ~/
ln -s $PWD/.oh-my-zsh ~/
ln -s $PWD/.gitconfig ~/
ln -s $PWD/.tmux.conf ~/
ln -s $PWD/.vimrc ~/
ln -s $PWD/.vim/bundle ~/.vim/bundle
ln -s $PWD/.Xdefaults ~/
ln -s $PWD/awesome ~/.config/awesome

source "$HOME/.zshrc"

tmux source-file "$HOME/.tmux.conf"
